# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Foodlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('spice_level', models.FloatField()),
                ('count', models.IntegerField()),
                ('item_image', models.ImageField(upload_to=b'')),
                ('availability', models.BooleanField(default=True)),
                ('pub_date', models.DateField()),
                ('price', models.FloatField()),
                ('event_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharePlate.Foodlist')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_spice_level', models.FloatField()),
                ('prefered_cost', models.FloatField()),
                ('prefered_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('rating', models.FloatField()),
                ('earnings', models.FloatField()),
                ('uid', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('organization', models.CharField(max_length=25)),
                ('image', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharePlate.Users'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharePlate.Users'),
        ),
        migrations.AddField(
            model_name='foodlist',
            name='chef_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharePlate.Users'),
        ),
        migrations.AddField(
            model_name='badge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharePlate.Users'),
        ),
    ]
