# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharePLate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlist',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='foodlist',
            name='spice_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='prefered_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user_spice_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='earnings',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='rating',
            field=models.FloatField(),
        ),
    ]
