# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharePlate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='location',
            field=models.CharField(default='Canberra', max_length=50),
            preserve_default=False,
        ),
    ]
