# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharePlate', '0002_users_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='event_location',
            field=models.CharField(default='Canberra Bus stop', max_length=50),
            preserve_default=False,
        ),
    ]
