# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharePlate', '0004_foodlist_cusine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='cusine',
        ),
    ]
