# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharePlate', '0005_remove_foodlist_cusine'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='cusine',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
