# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharePlate', '0007_purchases_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
